import os
import json
import fitz  # PyMuPDF

from google import genai
from telegram import (
    Update,
    InlineKeyboardButton,
    InlineKeyboardMarkup,
    Poll
)
from telegram.ext import (
    ApplicationBuilder,
    CommandHandler,
    CallbackQueryHandler,
    MessageHandler,
    filters,
    ContextTypes
)


# =========================================================
# ENVIRONMENT VARIABLES
# =========================================================

BOT_TOKEN = os.getenv("BOT_TOKEN")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

if not BOT_TOKEN:
    raise ValueError("BOT_TOKEN is missing")

if not GEMINI_API_KEY:
    raise ValueError("GEMINI_API_KEY is missing")


# =========================================================
# GEMINI
# =========================================================

client = genai.Client(api_key=GEMINI_API_KEY)

GEMINI_MODEL = "gemini-2.5-flash"


# =========================================================
# BRAND
# =========================================================

FOOTER_SIGNATURE = (
    "\n\n"
    "─── ✦ ───\n"
    "✦ Generated by: Mohammed Eskander\n"
    "𝙼𝚘𝚑𝚊𝚖𝚖𝚎𝚍 𝙴𝚜𝚔𝚊𝚗𝚍𝚎𝚛 𝙰𝙻𝚣𝚊𝚋𝚒𝚍𝚎'𝚎"
)


# =========================================================
# /START
# =========================================================

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):

    welcome_text = (
        "✨ <b>مرحباً بك في Eskander AI Studio!</b> ✨\n\n"

        "🤖 منصتك الأكاديمية الذكية لمعالجة المحاضرات "
        "والملفات باستخدام Google Gemini.\n\n"

        "📚 <b>الخدمات المتاحة:</b>\n\n"

        "🔹 <b>تلخيص المحاضرات</b>\n"
        "تلخيص منظم وواضح لأهم الأفكار والنقاط الرئيسية.\n\n"

        "🔹 <b>الاختبارات التفاعلية</b>\n"
        "إنشاء أسئلة اختيار من متعدد من محتوى المحاضرة "
        "مع تصحيح الإجابة وشرحها.\n\n"

        "🔹 <b>ترجمة المحاضرات</b>\n"
        "ترجمة أكاديمية واضحة للمحتوى إلى العربية.\n\n"

        "🔹 <b>معالجة ملفات PDF</b>\n"
        "إرسال ملف المحاضرة واختيار الخدمة المطلوبة مباشرة.\n\n"

        "👨‍💻 <b>المطور:</b>\n"
        "م/ محمد إسكندر الزبيدي\n"
        "𝙼𝚘𝚑𝚊𝚖𝚖𝚎𝚍 𝙴𝚜𝚔𝚊𝚗𝚍𝚎𝚛 𝙰𝙻𝚣𝚊𝚋𝚒𝚍𝚎'𝚎"

        f"{FOOTER_SIGNATURE}"
    )

    keyboard = [
        [
            InlineKeyboardButton(
                "📸 متابعة على إنستغرام",
                url="https://instagram.com/3men.1"
            ),
            InlineKeyboardButton(
                "💬 التواصل مع المطور",
                url="https://t.me/3men_1"
            )
        ],
        [
            InlineKeyboardButton(
                "🚀 بدء استخدام البوت",
                callback_data="go_to_services"
            )
        ]
    ]

    reply_markup = InlineKeyboardMarkup(keyboard)

    await update.message.reply_text(
        welcome_text,
        parse_mode="HTML",
        reply_markup=reply_markup
    )


# =========================================================
# BUTTON HANDLER
# =========================================================

async def button_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE
):

    query = update.callback_query
    await query.answer()

    # -----------------------------------------------------
    # START SERVICES
    # -----------------------------------------------------

    if query.data == "go_to_services":

        instructions = (
            "📚 <b>جاهز لبدء معالجة المحاضرة!</b>\n\n"
            "📄 أرسل ملف المحاضرة بصيغة PDF الآن.\n\n"
            "بعد استلام الملف سأقوم بقراءته واستخراج محتواه، "
            "ثم ستظهر لك الخدمات المتاحة.\n\n"
            "اختر الخدمة التي تريدها من القائمة."
            f"{FOOTER_SIGNATURE}"
        )

        await query.edit_message_text(
            instructions,
            parse_mode="HTML"
        )

    # -----------------------------------------------------
    # SUMMARY
    # -----------------------------------------------------

    elif query.data.startswith("summary_"):

        lang = (
            "العربية"
            if query.data == "summary_ar"
            else "الإنجليزية"
        )

        await query.message.reply_text(
            f"⏳ جاري إنشاء ملخص المحاضرة باللغة {lang}..."
        )

        pdf_text = context.user_data.get("pdf_text", "")

        if not pdf_text:

            await query.message.reply_text(
                "❌ لم أجد محتوى المحاضرة.\n"
                "يرجى إرسال ملف PDF من جديد."
                f"{FOOTER_SIGNATURE}",
                parse_mode="HTML"
            )
            return

        prompt = f"""
أنت مساعد أكاديمي متخصص.

قم بتلخيص المحاضرة التالية باللغة {lang}.

الشروط:
- حافظ على المعلومات المهمة.
- لا تخترع معلومات غير موجودة في المحاضرة.
- استخدم عناوين واضحة.
- استخدم نقاط رئيسية وفرعية.
- اجعل الملخص مناسباً للمراجعة قبل الاختبار.
- إذا كانت هناك تعريفات أو قوانين أو مصطلحات مهمة، حافظ عليها.

نص المحاضرة:

{pdf_text[:12000]}
"""

        try:

            response = client.models.generate_content(
                model=GEMINI_MODEL,
                contents=prompt
            )

            final_response = (
                f"📝 <b>ملخص المحاضرة ({lang})</b>\n\n"
                f"{response.text}"
                f"{FOOTER_SIGNATURE}"
            )

            await query.message.reply_text(
                final_response,
                parse_mode="HTML"
            )

        except Exception as e:

            print("SUMMARY ERROR:", e)

            await query.message.reply_text(
                "❌ حدث خطأ أثناء إنشاء الملخص.\n"
                "تأكد من إعداد Gemini API ثم حاول مرة أخرى."
                f"{FOOTER_SIGNATURE}",
                parse_mode="HTML"
            )

    # -----------------------------------------------------
    # QUIZ
    # -----------------------------------------------------

    elif query.data == "quiz":

        await query.message.reply_text(
            "⏳ جاري إنشاء سؤال تفاعلي من المحاضرة..."
        )

        pdf_text = context.user_data.get("pdf_text", "")

        if not pdf_text:

            await query.message.reply_text(
                "❌ لم أجد محتوى المحاضرة.\n"
                "يرجى إرسال ملف PDF من جديد."
            )
            return

        prompt = f"""
اقرأ المحاضرة التالية وأنشئ سؤال اختيار من متعدد واحد فقط.

أريد النتيجة بصيغة JSON فقط، بدون Markdown وبدون أي كلام إضافي.

الشكل المطلوب:

{{
    "question": "السؤال",
    "options": [
        "الخيار الأول",
        "الخيار الثاني",
        "الخيار الثالث",
        "الخيار الرابع"
    ],
    "correct_index": 0,
    "explanation": "شرح مختصر للإجابة الصحيحة"
}}

الشروط:
- السؤال يجب أن يكون من محتوى المحاضرة.
- أربعة خيارات فقط.
- correct_index يبدأ من 0.
- إجابة صحيحة واحدة فقط.
- السؤال باللغة العربية.

المحاضرة:

{pdf_text[:10000]}
"""

        try:

            response = client.models.generate_content(
                model=GEMINI_MODEL,
                contents=prompt
            )

            clean_json = (
                response.text
                .replace("```json", "")
                .replace("```", "")
                .strip()
            )

            data = json.loads(clean_json)

            await context.bot.send_poll(
                chat_id=query.message.chat_id,
                question=data["question"],
                options=data["options"],
                type=Poll.QUIZ,
                correct_option_id=int(data["correct_index"]),
                explanation=data["explanation"],
                is_anonymous=False
            )

            await query.message.reply_text(
                "🎯 <b>تم إنشاء السؤال التفاعلي بنجاح!</b>"
                f"{FOOTER_SIGNATURE}",
                parse_mode="HTML"
            )

        except Exception as e:

            print("QUIZ ERROR:", e)

            await query.message.reply_text(
                "⚠️ تعذر إنشاء السؤال حالياً.\n"
                "حاول مرة أخرى بعد قليل."
                f"{FOOTER_SIGNATURE}",
                parse_mode="HTML"
            )

    # -----------------------------------------------------
    # TRANSLATION
    # -----------------------------------------------------

    elif query.data == "translate":

        await query.message.reply_text(
            "⏳ جاري ترجمة محتوى المحاضرة..."
        )

        pdf_text = context.user_data.get("pdf_text", "")

        if not pdf_text:

            await query.message.reply_text(
                "❌ لم أجد محتوى المحاضرة.\n"
                "يرجى إرسال ملف PDF من جديد."
            )
            return

        prompt = f"""
أنت مترجم أكاديمي.

ترجم محتوى المحاضرة التالية إلى اللغة العربية.

الشروط:
- ترجمة دقيقة وواضحة.
- حافظ على المصطلحات الأكاديمية.
- لا تضف معلومات من خارج النص.
- لا تحذف الأفكار المهمة.
- حافظ قدر الإمكان على ترتيب المحتوى.

نص المحاضرة:

{pdf_text[:12000]}
"""

        try:

            response = client.models.generate_content(
                model=GEMINI_MODEL,
                contents=prompt
            )

            final_response = (
                "🌐 <b>ترجمة المحاضرة</b>\n\n"
                f"{response.text}"
                f"{FOOTER_SIGNATURE}"
            )

            await query.message.reply_text(
                final_response,
                parse_mode="HTML"
            )

        except Exception as e:

            print("TRANSLATION ERROR:", e)

            await query.message.reply_text(
                "❌ حدث خطأ أثناء الترجمة.\n"
                "حاول مرة أخرى."
                f"{FOOTER_SIGNATURE}",
                parse_mode="HTML"
            )


# =========================================================
# PDF HANDLER
# =========================================================

async def handle_document(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE
):

    document = update.message.document

    if not document.file_name.lower().endswith(".pdf"):

        await update.message.reply_text(
            "⚠️ يرجى إرسال ملف بصيغة PDF فقط."
            f"{FOOTER_SIGNATURE}",
            parse_mode="HTML"
        )

        return

    status_msg = await update.message.reply_text(
        "📥 جاري استقبال ملف المحاضرة..."
    )

    pdf_path = f"temp_{document.file_unique_id}.pdf"

    try:

        file = await context.bot.get_file(
            document.file_id
        )

        await file.download_to_drive(pdf_path)

        await status_msg.edit_text(
            "📖 جاري قراءة وتحليل محتوى المحاضرة..."
        )

        doc = fitz.open(pdf_path)

        extracted_text = ""

        for page in doc:
            extracted_text += page.get_text()

        doc.close()

        if not extracted_text.strip():

            await status_msg.edit_text(
                "⚠️ لم أتمكن من استخراج نص من هذا الملف.\n"
                "قد يكون الملف عبارة عن صور ممسوحة ضوئياً."
            )

            return

        context.user_data["pdf_text"] = extracted_text

        keyboard = [
            [
                InlineKeyboardButton(
                    "📝 تلخيص بالعربي",
                    callback_data="summary_ar"
                ),
                InlineKeyboardButton(
                    "📝 Summary English",
                    callback_data="summary_en"
                )
            ],
            [
                InlineKeyboardButton(
                    "❓ اختبار تفاعلي",
                    callback_data="quiz"
                ),
                InlineKeyboardButton(
                    "🌐 ترجمة المحاضرة",
                    callback_data="translate"
                )
            ]
        ]

        reply_markup = InlineKeyboardMarkup(keyboard)

        await status_msg.edit_text(
            "✅ <b>تم استقبال المحاضرة بنجاح!</b>\n\n"
            f"📄 <b>اسم الملف:</b> {document.file_name}\n"
            f"📑 <b>عدد الصفحات:</b> {len(doc)}\n\n"
            "🎯 <b>اختر الخدمة المطلوبة:</b>"
            f"{FOOTER_SIGNATURE}",
            reply_markup=reply_markup,
            parse_mode="HTML"
        )

    except Exception as e:

        print("PDF ERROR:", e)

        await status_msg.edit_text(
            "❌ حدث خطأ أثناء قراءة ملف PDF.\n"
            "يرجى المحاولة مرة أخرى."
            f"{FOOTER_SIGNATURE}",
            parse_mode="HTML"
        )

    finally:

        if os.path.exists(pdf_path):
            os.remove(pdf_path)


# =========================================================
# ERROR HANDLER
# =========================================================

async def error_handler(
    update: object,
    context: ContextTypes.DEFAULT_TYPE
):

    print("BOT ERROR:", context.error)


# =========================================================
# RUN BOT
# =========================================================

def main():

    print("⚡ Starting Eskander AI Studio...")

    app = (
        ApplicationBuilder()
        .token(BOT_TOKEN)
        .build()
    )

    app.add_handler(
        CommandHandler("start", start)
    )

    app.add_handler(
        CallbackQueryHandler(button_handler)
    )

    app.add_handler(
        MessageHandler(
            filters.Document.PDF,
            handle_document
        )
    )

    app.add_error_handler(error_handler)

    print("✅ Bot is running...")

    app.run_polling()


if __name__ == "__main__":
    main()
