import os
import json
import threading
import html
from http.server import BaseHTTPRequestHandler, HTTPServer

import fitz
from google import genai

from reportlab.lib.pagesizes import A4
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_RIGHT

import arabic_reshaper
from bidi.algorithm import get_display

from telegram import (
    Update,
    InlineKeyboardButton,
    InlineKeyboardMarkup,
    Poll
)

from telegram.ext import (
    ApplicationBuilder,
    CommandHandler,
    CallbackQueryHandler,
    MessageHandler,
    filters,
    ContextTypes
)


# =========================
# ENVIRONMENT VARIABLES
# =========================

BOT_TOKEN = os.getenv("BOT_TOKEN")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

if not BOT_TOKEN:
    raise ValueError("BOT_TOKEN is missing")

if not GEMINI_API_KEY:
    raise ValueError("GEMINI_API_KEY is missing")


# =========================
# GEMINI
# =========================

client = genai.Client(api_key=GEMINI_API_KEY)

GEMINI_MODEL = "gemini-3.8-flash"


# =========================
# BRAND
# =========================

FOOTER_SIGNATURE = (
    "\n\n"
    "─── ✦ ───\n"
    "✦ Generated by: Mohammed Eskander\n"
    "𝙼𝚘𝚑𝚊𝚖𝚖𝚎𝚍 𝙴𝚜𝚔𝚊𝚗𝚍𝚎𝚛 𝙰𝙻𝚣𝚊𝚋𝚒𝚍𝚎'𝚎"
)


# =========================
# PDF FONT
# =========================

FONT_PATHS = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    "/usr/share/fonts/dejavu/DejaVuSans.ttf"
]

FONT_PATH = None

for path in FONT_PATHS:
    if os.path.exists(path):
        FONT_PATH = path
        break

if FONT_PATH:
    pdfmetrics.registerFont(
        TTFont("DejaVuSans", FONT_PATH)
    )
else:
    print("WARNING: Arabic font was not found.")


# =========================
# CREATE PDF
# =========================

def shape_arabic(text):
    reshaped = arabic_reshaper.reshape(text)
    return get_display(reshaped)


def create_text_pdf(text, title, output_path):
    if not FONT_PATH:
        raise FileNotFoundError(
            "Arabic PDF font was not found."
        )

    document = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=45,
        leftMargin=45,
        topMargin=45,
        bottomMargin=45
    )

    title_style = ParagraphStyle(
        "TitleStyle",
        fontName="DejaVuSans",
        fontSize=16,
        leading=25,
        alignment=TA_RIGHT,
        spaceAfter=20
    )

    text_style = ParagraphStyle(
        "TextStyle",
        fontName="DejaVuSans",
        fontSize=11,
        leading=20,
        alignment=TA_RIGHT,
        spaceAfter=8
    )

    footer_style = ParagraphStyle(
        "FooterStyle",
        fontName="DejaVuSans",
        fontSize=9,
        leading=16,
        alignment=TA_RIGHT,
        spaceBefore=20
    )

    story = []

    title_display = shape_arabic(title)

    story.append(
        Paragraph(
            html.escape(title_display),
            title_style
        )
    )

    for line in text.splitlines():

        line = line.strip()

        if not line:
            story.append(
                Spacer(1, 8)
            )
            continue

        line_display = shape_arabic(line)

        safe_line = html.escape(
            line_display
        )

        story.append(
            Paragraph(
                safe_line,
                text_style
            )
        )

    story.append(
        Spacer(1, 20)
    )

    footer_text = (
        "─── ✦ ───<br/>"
        "✦ Generated by: Mohammed Eskander<br/>"
        "Mohammed Eskander ALzabidee"
    )

    footer_display = shape_arabic(
        footer_text.replace("<br/>", "\n")
    )

    footer_display = (
        footer_display
        .replace("\n", "<br/>")
    )

    story.append(
        Paragraph(
            footer_display,
            footer_style
        )
    )

    document.build(story)


# =========================
# RENDER HEALTH SERVER
# =========================

class HealthHandler(BaseHTTPRequestHandler):

    def do_GET(self):
        self.send_response(200)
        self.end_headers()
        self.wfile.write(
            b"Eskander AI Studio is running!"
        )

    def log_message(self, format, *args):
        return


def start_health_server():

    port = int(
        os.environ.get(
            "PORT",
            10000
        )
    )

    server = HTTPServer(
        ("0.0.0.0", port),
        HealthHandler
    )

    print(
        f"Health server running on port {port}"
    )

    server.serve_forever()


# =========================
# START COMMAND
# =========================

async def start(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE
):

    welcome_text = (
        "✨ <b>مرحبًا بك في Eskander AI Studio!</b> ✨\n\n"

        "🤖 منصتك الأكاديمية الذكية لمعالجة المحاضرات "
        "والملفات باستخدام Google Gemini.\n\n"

        "📚 <b>الخدمات المتاحة:</b>\n\n"

        "🔹 <b>تلخيص المحاضرات</b>\n"
        "إنشاء ملخص منظم وواضح لأهم الأفكار والنقاط الرئيسية.\n\n"

        "🔹 <b>الاختبارات التفاعلية</b>\n"
        "إنشاء أسئلة اختيار من متعدد من محتوى المحاضرة "
        "مع تصحيح الإجابة وشرحها.\n\n"

        "🔹 <b>ترجمة المحاضرات</b>\n"
        "ترجمة أكاديمية واضحة للمحتوى إلى العربية.\n\n"

        "🔹 <b>معالجة ملفات PDF</b>\n"
        "إرسال ملف المحاضرة واختيار الخدمة المطلوبة مباشرة.\n\n"

        "👨‍💻 <b>المطور:</b>\n"
        "م/ محمد إسكندر الزبيدي\n\n"

        f"{FOOTER_SIGNATURE}"
    )

    keyboard = [
        [
            InlineKeyboardButton(
                "📸 متابعة على إنستجرام",
                url="https://instagram.com/3men.1"
            ),
            InlineKeyboardButton(
                "💬 التواصل مع المطور",
                url="https://t.me/3men_1"
            )
        ],
        [
            InlineKeyboardButton(
                "🚀 بدء استخدام البوت",
                callback_data="go_to_services"
            )
        ]
    ]

    reply_markup = InlineKeyboardMarkup(
        keyboard
    )

    await update.message.reply_text(
        welcome_text,
        parse_mode="HTML",
        reply_markup=reply_markup
    )


# =========================
# BUTTON HANDLER
# =========================

async def button_handler(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE
):

    query = update.callback_query

    await query.answer()


    # =====================
    # START SERVICES
    # =====================

    if query.data == "go_to_services":

        instructions = (
            "📚 <b>جاهز لبدء معالجة المحاضرة!</b>\n\n"

            "📄 أرسل ملف المحاضرة بصيغة PDF.\n\n"

            "بعد استلام الملف سأقوم بقراءة محتواه "
            "واستخراج النص، ثم ستظهر لك الخدمات المتاحة.\n\n"

            "اختر الخدمة التي تريدها من القائمة.\n\n"

            f"{FOOTER_SIGNATURE}"
        )

        await query.edit_message_text(
            instructions,
            parse_mode="HTML"
        )


    # =====================
    # SUMMARY
    # =====================

    elif query.data.startswith("summary_"):

        lang = (
            "العربية"
            if query.data == "summary_ar"
            else "الإنجليزية"
        )

        await query.message.reply_text(
            f"⏳ جاري إنشاء ملخص المحاضرة باللغة {lang}..."
        )

        pdf_text = context.user_data.get(
            "pdf_text",
            ""
        )

        if not pdf_text:

            await query.message.reply_text(
                "❌ لم أجد محتوى المحاضرة.\n"
                "يرجى إرسال ملف PDF من جديد."
            )

            return


        prompt = f"""
أنت مساعد أكاديمي متخصص.

قم بتلخيص المحاضرة التالية باللغة {lang}.

الشروط:

- حافظ على المعلومات المهمة الموجودة في المحاضرة.
- لا تخترع معلومات غير موجودة في المحاضرة.
- استخدم عناوين واضحة.
- استخدم نقاطًا رئيسية وفرعية.
- اجعل الملخص مناسبًا للمراجعة قبل الاختبار.
- إذا كانت هناك تعريفات أو قوانين أو مصطلحات مهمة، حافظ عليها.
- لا تضف معلومات من خارج المحاضرة.
- اجعل الناتج منظمًا وواضحًا.
- لا تستخدم مقدمة طويلة أو كلامًا غير ضروري.

نص المحاضرة:

{pdf_text[:12000]}
"""

        try:

            response = client.models.generate_content(
                model=GEMINI_MODEL,
                contents=prompt
            )

            summary_text = response.text

            pdf_path = (
                f"summary_{query.from_user.id}.pdf"
            )

            create_text_pdf(
                summary_text,
                f"ملخص المحاضرة - {lang}",
                pdf_path
            )

            try:

                with open(
                    pdf_path,
                    "rb"
                ) as pdf_file:

                    await query.message.reply_document(
                        document=pdf_file,
                        caption=(
                            "📚 تم إنشاء ملخص المحاضرة بنجاح.\n\n"
                            "✦ Generated by: Mohammed Eskander"
                        )
                    )

            finally:

                if os.path.exists(pdf_path):
                    os.remove(pdf_path)

        except Exception as e:

            print(
                "SUMMARY ERROR:",
                e
            )

            await query.message.reply_text(
                "❌ حدث خطأ أثناء إنشاء الملخص.\n"
                "يرجى المحاولة مرة أخرى."
            )


    # =====================
    # QUIZ
    # =====================

    elif query.data == "quiz":

        await query.message.reply_text(
            "⏳ جاري إنشاء سؤال تفاعلي من المحاضرة..."
        )

        pdf_text = context.user_data.get(
            "pdf_text",
            ""
        )

        if not pdf_text:

            await query.message.reply_text(
                "❌ لم أجد محتوى المحاضرة.\n"
                "يرجى إرسال ملف PDF من جديد."
            )

            return


        prompt = f"""
اقرأ المحاضرة التالية وأنشئ سؤال اختيار من متعدد واحد فقط.

أريد النتيجة بصيغة JSON فقط، بدون Markdown وبدون أي كلام إضافي.

الشكل المطلوب:

{{
    "question": "السؤال",
    "options": [
        "الخيار الأول",
        "الخيار الثاني",
        "الخيار الثالث",
        "الخيار الرابع"
    ],
    "correct_index": 0,
    "explanation": "شرح مختصر للإجابة الصحيحة"
}}

الشروط:

- السؤال يجب أن يكون من محتوى المحاضرة.
- أربعة خيارات فقط.
- correct_index يبدأ من 0.
- إجابة صحيحة واحدة فقط.
- السؤال باللغة العربية.
- الخيارات باللغة العربية.
- الشرح باللغة العربية.

المحاضرة:

{pdf_text[:10000]}
"""

        try:

            response = client.models.generate_content(
                model=GEMINI_MODEL,
                contents=prompt
            )

            clean_json = (
                response.text
                .replace("```json", "")
                .replace("```", "")
                .strip()
            )

            data = json.loads(
                clean_json
            )

            await context.bot.send_poll(
                chat_id=query.message.chat_id,

                question=data["question"],

                options=data["options"],

                type=Poll.QUIZ,

                correct_option_id=int(
                    data["correct_index"]
                ),

                explanation=data["explanation"],

                is_anonymous=False
            )

            await query.message.reply_text(
                "🎯 تم إنشاء السؤال التفاعلي بنجاح!"
            )

        except Exception as e:

            print(
                "QUIZ ERROR:",
                e
            )

            await query.message.reply_text(
                "❌ تعذر إنشاء السؤال حاليًا.\n"
                "حاول مرة أخرى بعد قليل."
            )


    # =====================
    # TRANSLATION
    # =====================

    elif query.data == "translate":

        await query.message.reply_text(
            "⏳ جاري ترجمة محتوى المحاضرة..."
        )

        pdf_text = context.user_data.get(
            "pdf_text",
            ""
        )

        if not pdf_text:

            await query.message.reply_text(
                "❌ لم أجد محتوى المحاضرة.\n"
                "يرجى إرسال ملف PDF من جديد."
            )

            return


        prompt = f"""
أنت مترجم أكاديمي متخصص.

ترجم محتوى المحاضرة التالية إلى اللغة العربية.

الشروط:

- ترجمة دقيقة وواضحة.
- حافظ على المصطلحات الأكاديمية المهمة.
- لا تضف معلومات من خارج النص.
- لا تحذف الأفكار المهمة.
- حافظ قدر الإمكان على ترتيب المحتوى.
- اجعل الترجمة مناسبة للطلاب والمراجعة.
- لا تضف مقدمة أو خاتمة غير موجودة في النص.

نص المحاضرة:

{pdf_text[:12000]}
"""

        try:

            response = client.models.generate_content(
                model=GEMINI_MODEL,
                contents=prompt
            )

            translation_text = response.text

            pdf_path = (
                f"translation_{query.from_user.id}.pdf"
            )

            create_text_pdf(
                translation_text,
                "ترجمة المحاضرة",
                pdf_path
            )

            try:

                with open(
                    pdf_path,
                    "rb"
                ) as pdf_file:

                    await query.message.reply_document(
                        document=pdf_file,
                        caption=(
                            "🌐 تم إنشاء ترجمة المحاضرة بنجاح.\n\n"
                            "✦ Generated by: Mohammed Eskander"
                        )
                    )

            finally:

                if os.path.exists(pdf_path):
                    os.remove(pdf_path)

        except Exception as e:

            print(
                "TRANSLATION ERROR:",
                e
            )

            await query.message.reply_text(
                "❌ حدث خطأ أثناء الترجمة.\n"
                "حاول مرة أخرى."
            )


# =========================
# PDF HANDLER
# =========================

async def handle_document(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE
):

    document = update.message.document

    if not document.file_name.lower().endswith(".pdf"):

        await update.message.reply_text(
            "⚠️ يرجى إرسال ملف بصيغة PDF فقط."
        )

        return


    status_msg = await update.message.reply_text(
        "📥 جاري استقبال ملف المحاضرة..."
    )


    pdf_path = (
        f"temp_{document.file_unique_id}.pdf"
    )


    try:

        file = await context.bot.get_file(
            document.file_id
        )

        await file.download_to_drive(
            pdf_path
        )

        await status_msg.edit_text(
            "📖 جاري قراءة وتحليل محتوى المحاضرة..."
        )

        doc = fitz.open(
            pdf_path
        )

        page_count = len(doc)

        extracted_text = ""

        for page in doc:
            extracted_text += page.get_text()

        doc.close()


        if not extracted_text.strip():

            await status_msg.edit_text(
                "⚠️ لم أتمكن من استخراج نص من هذا الملف.\n"
                "قد يكون الملف عبارة عن صور ممسوحة ضوئيًا."
            )

            return


        context.user_data["pdf_text"] = extracted_text


        keyboard = [

            [

                InlineKeyboardButton(
                    "📚 تلخيص بالعربي",
                    callback_data="summary_ar"
                ),

                InlineKeyboardButton(
                    "📚 Summary English",
                    callback_data="summary_en"
                )

            ],

            [

                InlineKeyboardButton(
                    "📝 اختبار تفاعلي",
                    callback_data="quiz"
                ),

                InlineKeyboardButton(
                    "🌐 ترجمة المحاضرة",
                    callback_data="translate"
                )

            ]

        ]


        reply_markup = InlineKeyboardMarkup(
            keyboard
        )


        await status_msg.edit_text(

            "✅ <b>تم استقبال المحاضرة بنجاح!</b>\n\n"

            f"📄 <b>اسم الملف:</b> "
            f"{html.escape(document.file_name)}\n"

            f"📑 <b>عدد الصفحات:</b> "
            f"{page_count}\n\n"

            "🎯 <b>اختر الخدمة المطلوبة:</b>\n\n"

            "📚 التلخيص والترجمة سيتم إرسالهما كملف PDF.",

            reply_markup=reply_markup,

            parse_mode="HTML"
        )


    except Exception as e:

        print(
            "PDF ERROR:",
            e
        )

        await status_msg.edit_text(
            "❌ حدث خطأ أثناء قراءة ملف PDF.\n"
            "يرجى المحاولة مرة أخرى."
        )


    finally:

        if os.path.exists(pdf_path):

            os.remove(pdf_path)


# =========================
# ERROR HANDLER
# =========================

async def error_handler(
    update: object,
    context: ContextTypes.DEFAULT_TYPE
):

    print(
        "BOT ERROR:",
        context.error
    )


# =========================
# MAIN
# =========================

def main():

    print(
        "⚡ Starting Eskander AI Studio..."
    )


    threading.Thread(
        target=start_health_server,
        daemon=True
    ).start()


    app = (
        ApplicationBuilder()
        .token(BOT_TOKEN)
        .build()
    )


    app.add_handler(
        CommandHandler(
            "start",
            start
        )
    )


    app.add_handler(
        CallbackQueryHandler(
            button_handler
        )
    )


    app.add_handler(
        MessageHandler(
            filters.Document.PDF,
            handle_document
        )
    )


    app.add_error_handler(
        error_handler
    )


    print(
        "✅ Bot is running..."
    )


    app.run_polling()


# =========================
# RUN
# =========================

if __name__ == "__main__":

    main()
