import os
import fitz  # PyMuPDF
from groq import Groq
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import Application, CommandHandler, MessageHandler, CallbackQueryHandler, ContextTypes, filters

# المفاتيح الخاصة بك
TELEGRAM_TOKEN = "8210964268:AAF1enhyC-I89HQh17J8VB2lz6cpoonxyv4"
GROQ_API_KEY = "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"

# التوقيع الخاص بك
SIGNATURE = "\n\n─── ✦ ───\n✦ Generated by: Mohammed Eskander"

client = Groq(api_key=GROQ_API_KEY)
user_pdf_texts = {}

def ask_ai(prompt_text):
    """دالة إرسال الطلب لموديل Llama 3.3 عبر Groq"""
    response = client.chat.completions.create(
        messages=[{"role": "user", "content": prompt_text}],
        model="llama-3.3-70b-versatile",
    )
    return response.choices[0].message.content

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    welcome_text = (
        "مرحباً بك في **Eskander AI Studio** 📚✨\n\n"
        "أرسل لي أي ملف محاضرة بصيغة PDF، وسأقوم بتلخيصه، ترجمته، أو إنشاء اختبار تفاعلي منه!"
        f"{SIGNATURE}"
    )
    await update.message.reply_text(welcome_text, parse_mode="Markdown")

async def handle_document(update: Update, context: ContextTypes.DEFAULT_TYPE):
    document = update.message.document
    if not document.file_name.lower().endswith('.pdf'):
        await update.message.reply_text("عذراً، يرجى إرسال ملف بصيغة PDF فقط.")
        return

    status_msg = await update.message.reply_text("⏳ جاري قراءة وتحليل ملف الـ PDF...")
    
    file = await context.bot.get_file(document.file_id)
    file_path = f"temp_{update.message.from_user.id}.pdf"
    await file.download_to_drive(file_path)

    try:
        doc = fitz.open(file_path)
        extracted_text = ""
        for page in doc:
            extracted_text += page.get_text() + "\n"
        doc.close()

        if os.path.exists(file_path):
            os.remove(file_path)

        extracted_text = extracted_text.strip()
        
        if not extracted_text or len(extracted_text) < 30:
            await status_msg.edit_text("❌ تعذر استخراج نص كافٍ من الملف.")
            return

        user_pdf_texts[update.message.from_user.id] = extracted_text[:6000]

        keyboard = [
            [InlineKeyboardButton("📝 ملخص بالعربي", callback_data="summarize")],
            [InlineKeyboardButton("🌐 ترجمة المحاضرة", callback_data="translate")],
            [InlineKeyboardButton("❓ إنشاء اختبار تفاعلي", callback_data="quiz")]
        ]
        reply_markup = InlineKeyboardMarkup(keyboard)

        await status_msg.edit_text(
            "✅ تم استخراج النص بنجاح! اختر العملية المطلوبة من الأسفل:",
            reply_markup=reply_markup
        )

    except Exception as e:
        if os.path.exists(file_path):
            os.remove(file_path)
        await status_msg.edit_text(f"حدث خطأ أثناء معالجة الملف: {str(e)}")

async def handle_button(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    await query.answer()

    user_id = query.from_user.id
    if user_id not in user_pdf_texts:
        await query.edit_message_text("❌ انتهت الجلسة. يرجى إرسال ملف الـ PDF مرة أخرى.")
        return

    text_content = user_pdf_texts[user_id]
    action = query.data

    await query.edit_message_text("⚡ جاري التوليد باستخدام الذكاء الاصطناعي...")

    try:
        if action == "summarize":
            prompt = f"قدم ملخصاً شاملاً ومنظماً للمادة التالية باللغة العربية في شكل نقاط رئيسية:\n\n{text_content}"
        elif action == "translate":
            prompt = f"ترجم المفاهيم والنقاط الأساسية للنص التالي إلى اللغة العربية بشكل شارح ومبسط:\n\n{text_content}"
        elif action == "quiz":
            prompt = f"أنشئ اختباراً مكوناً من 5 أسئلة اختيار من متعدد بناءً على النص التالي باللغة العربية مع تحديد الإجابة الصحيحة:\n\n{text_content}"

        res_text = ask_ai(prompt)
        
        if len(res_text) > 3800:
            res_text = res_text[:3800] + "\n\n[تم اختصار باقي النص لتجاوز حد الرسالة]"
        
        await query.edit_message_text(res_text + SIGNATURE)

    except Exception as e:
        await query.edit_message_text(f"حدث خطأ أثناء الاتصال بالذكاء الاصطناعي: {str(e)}")

def main():
    app = Application.builder().token(TELEGRAM_TOKEN).build()

    app.add_handler(CommandHandler("start", start))
    app.add_handler(MessageHandler(filters.Document.ALL, handle_document))
    app.add_handler(CallbackQueryHandler(handle_button))

    print("⚡ البوت يعمل الآن بنجاح...")
    app.run_polling()

if __name__ == "__main__":
    main()
